"""
Report Generator Module - HTML and JSON report generation.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Any
from rich.console import Console

console = Console()

# HTML template for reports
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ForensicAutomator Report - {title}</title>
    <style>
        :root {{
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --bg-card: #21262d;
            --text-primary: #c9d1d9;
            --text-secondary: #8b949e;
            --accent: #58a6ff;
            --danger: #f85149;
            --warning: #d29922;
            --success: #3fb950;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            line-height: 1.6;
            padding: 2rem;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        header {{
            background: linear-gradient(135deg, #238636 0%, #1f6feb 100%);
            padding: 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
        }}
        h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
        .meta {{ color: rgba(255,255,255,0.8); font-size: 0.9rem; }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }}
        .stat-card {{
            background: var(--bg-card);
            padding: 1.5rem;
            border-radius: 8px;
            border-left: 4px solid var(--accent);
        }}
        .stat-card.danger {{ border-left-color: var(--danger); }}
        .stat-card.warning {{ border-left-color: var(--warning); }}
        .stat-card.success {{ border-left-color: var(--success); }}
        .stat-value {{ font-size: 2rem; font-weight: bold; }}
        .stat-label {{ color: var(--text-secondary); font-size: 0.85rem; }}
        section {{
            background: var(--bg-secondary);
            border-radius: 12px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
        }}
        h2 {{
            color: var(--accent);
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid var(--bg-card);
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9rem;
        }}
        th, td {{
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid var(--bg-card);
        }}
        th {{ color: var(--text-secondary); font-weight: 500; }}
        tr:hover {{ background: var(--bg-card); }}
        .badge {{
            display: inline-block;
            padding: 0.25rem 0.5rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 500;
        }}
        .badge-danger {{ background: rgba(248,81,73,0.2); color: var(--danger); }}
        .badge-warning {{ background: rgba(210,153,34,0.2); color: var(--warning); }}
        .badge-success {{ background: rgba(63,185,80,0.2); color: var(--success); }}
        .badge-info {{ background: rgba(88,166,255,0.2); color: var(--accent); }}
        code {{
            background: var(--bg-card);
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-family: 'Fira Code', monospace;
            font-size: 0.85rem;
        }}
        footer {{
            text-align: center;
            color: var(--text-secondary);
            padding: 2rem;
            font-size: 0.85rem;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🔍 ForensicAutomator Report</h1>
            <p class="meta">Generated: {timestamp} | Type: {report_type}</p>
        </header>
        
        <div class="summary">
            {summary_cards}
        </div>
        
        {sections}
        
        <footer>
            Generated by ForensicAutomator v0.1.0 | Cross-platform Cybersecurity Forensic Tool
        </footer>
    </div>
</body>
</html>
"""


class ReportBuilder:
    """Build forensic reports in various formats."""

    def __init__(self, title: str = "Forensic Analysis"):
        self.title = title
        self.timestamp = datetime.now().isoformat()
        self.data: dict[str, Any] = {
            "title": title,
            "timestamp": self.timestamp,
            "sections": {},
            "summary": {},
        }

    def add_summary(self, key: str, value: Any, severity: str = "info") -> None:
        """Add a summary statistic."""
        self.data["summary"][key] = {"value": value, "severity": severity}

    def add_section(self, name: str, data: list[dict]) -> None:
        """Add a data section to the report."""
        self.data["sections"][name] = data

    def to_json(self) -> str:
        """Export report as JSON."""
        return json.dumps(self.data, indent=2, default=str)

    def to_html(self) -> str:
        """Export report as HTML."""
        # Build summary cards
        summary_cards = ""
        for key, info in self.data["summary"].items():
            severity_class = info.get("severity", "info")
            if severity_class == "critical":
                severity_class = "danger"
            summary_cards += f"""
            <div class="stat-card {severity_class}">
                <div class="stat-value">{info['value']}</div>
                <div class="stat-label">{key}</div>
            </div>
            """

        # Build sections
        sections_html = ""
        for section_name, rows in self.data["sections"].items():
            if not rows:
                continue

            # Build table
            headers = rows[0].keys() if rows else []
            header_row = "".join(f"<th>{h}</th>" for h in headers)

            body_rows = ""
            for row in rows:
                cells = ""
                for key, val in row.items():
                    # Apply styling based on content
                    if isinstance(val, str):
                        if "critical" in val.lower() or "high" in val.lower():
                            val = f'<span class="badge badge-danger">{val}</span>'
                        elif "warning" in val.lower() or "medium" in val.lower():
                            val = f'<span class="badge badge-warning">{val}</span>'
                        elif "success" in val.lower() or "normal" in val.lower():
                            val = f'<span class="badge badge-success">{val}</span>'
                    cells += f"<td>{val}</td>"
                body_rows += f"<tr>{cells}</tr>"

            sections_html += f"""
            <section>
                <h2>{section_name}</h2>
                <table>
                    <thead><tr>{header_row}</tr></thead>
                    <tbody>{body_rows}</tbody>
                </table>
            </section>
            """

        return HTML_TEMPLATE.format(
            title=self.title,
            timestamp=self.timestamp,
            report_type=self.title,
            summary_cards=summary_cards,
            sections=sections_html,
        )

    def save(self, path: str, format: str = "html") -> None:
        """Save report to file."""
        output_path = Path(path)

        if format == "json":
            content = self.to_json()
            if not output_path.suffix:
                output_path = output_path.with_suffix(".json")
        else:
            content = self.to_html()
            if not output_path.suffix:
                output_path = output_path.with_suffix(".html")

        output_path.write_text(content, encoding="utf-8")
        console.print(f"[green]✓ Report saved:[/green] {output_path}")


def generate_report(
    title: str,
    summary: dict[str, tuple[Any, str]],
    sections: dict[str, list[dict]],
    output_path: str,
    format: str = "html",
) -> None:
    """
    Generate and save a forensic report.

    Args:
        title: Report title.
        summary: Dict of {label: (value, severity)}.
        sections: Dict of {section_name: [row_dicts]}.
        output_path: Where to save the report.
        format: 'html' or 'json'.
    """
    builder = ReportBuilder(title)

    for key, (value, severity) in summary.items():
        builder.add_summary(key, value, severity)

    for section_name, data in sections.items():
        builder.add_section(section_name, data)

    builder.save(output_path, format)
